# Generated by Django 6.1.1 on 2026-09-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_asset_created_by_asset_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='accountability_scan',
            field=models.FileField(blank=True, null=True, upload_to='accountability_scans/'),
        ),
    ]
