# Generated by Django 4.2.30 on 2026-09-13 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_asset_accountability_scan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="assigned_to",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="laptopspec",
            name="gpu",
            field=models.CharField(blank=True, default="N/A", max_length=50, null=""),
            preserve_default=False,
        ),
    ]
